# This is an example configuration file. Copy to config.yaml and add your apikey to use it properly.
api_key: example-api-key
organization_id: example-organization-id
# Determines how many times to rerequest completions before returning nothing
max_retries: 8
# Output raw values
debug: true