# This is an example configuration file. Copy to config.yaml and add your apikey to use it properly.
api_key: example-api-key
organization_id: example-organization-id
# The GPT model to use. Either: "gpt-3.5-turbo" or "gpt-4"
model: "gpt-3.5-turbo"
# Determines how many times to rerequest completions before returning nothing
max_retries: 8
# Output raw values
debug: true