language: py
output_dir: experiments/
prompt_num: 1
prompts:
- '{}'
- 'Please finish this function: {}'
- 'Write the function for me that fulfills the prompt: {}'
- Please write the entire function that matches {}
- Please provide a unique solution that complete the function that starts with {}
- "I have a function prompt ```{}```\n Please produce the function for me which completes\
  \ this prompt."
system_role: 0
system_roles:
- You are a programmer whose job it is to finish the functions provided by the user.
- You're job is to write the functions asked of you by the user.
- you are a large language model whose job it is to complete code prompts, determining
  the language to be written in based on the apparent language of the prompt.
- You are a language model whose job it is to produce the full function that fulfills
  the prompt.
- You are the model Codex whose job it is to write an entire function given a function
  prompt.
