language: py
output_dir: experiments/
prompt_num: 1
prompts:
- 'Write the function for me that fulfills the prompt: {}'
- Please write the entire function that matches {}
- Please provide a unique solution that complete the function that starts with {}
- "I have a function prompt ```{}```\n Please produce the function for me which completes\
  \ this prompt."
system_role: 0
system_roles:
- You are a programmer whose job it is to finish the functions provided by the user.
- Your job is to write the functions asked of you by the user.
- You are a language model whose job it is to produce the full function that fulfills
  the prompt.
