system_role: 0
prompt_lead: 0
language: "py"
system_roles: 
- "You are a programmer whose job it is to finish the functions provided by the user."
- "You're job is to write the functions asked of you by the user."
- "you are a large language model whose job it is to complete code prompts, \
  determining the language to be written in based on the apparent language of the prompt."
- "You are a language model whose job it is to produce the full function that fulfills the prompt."
prompt_leads:
- "{}"
- "Please finish this function: {}"
- "Write the function for me that fulfills the prompt: {}"
- "Please write the entire function that matches {}"
